version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: gophermart-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./gophermart-mongo:/data/db
  postgres:
    image: postgres:13.6
    container_name: gophermart-postgres
    environment:
      POSTGRES_USER: gophermart-postgres
      POSTGRES_PASSWORD: gophermart-postgres
      POSTGRES_DB: gophermart-postgres
    volumes:
      - ./gophermart-postgres:/var/lib/postgresql/data
    ports:
      - "3000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    command: [ "postgres", "-c", "log_statement=all" ]
  gophermart:
    build:
      context: .
      dockerfile: DockerfileGophermart
    depends_on:
      - mongodb
      - postgres
      - accrual
    environment:
      - DATABASE_URI=${GOPHERMART_DATABASE_URI}
      - ACCRUAL_ADDRESS=${ACCRUAL_ADDRESS}
      - RUN_ADDRESS=${GOPHERMART_RUN_ADDRESS}
    ports:
      - "8080:8080"
  accrual:
    build:
      context: .
      dockerfile: DockerfileAccrual
    depends_on:
      - postgres
    environment:
      - DATABASE_URI=${ACCRUAL_DATABASE_URI}
      - RUN_ADDRESS=${ACCRUAL_RUN_ADDRESS}
