-- +goose Up
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY, number VARCHAR(100) UNIQUE, status VARCHAR(10), accrual DOUBLE PRECISION);
CREATE TABLE IF NOT EXISTS goods(id SERIAL PRIMARY KEY, match VARCHAR(100) UNIQUE, reward DOUBLE PRECISION, reward_type VARCHAR(2));
CREATE INDEX IF NOT EXISTS orders_num_idx ON orders USING hash (number);
CREATE INDEX IF NOT EXISTS goods_match_idx ON goods USING hash (match);
COMMIT;

-- +goose Down
BEGIN TRANSACTION;
DROP TABLE IF EXISTS orders, goods;
COMMIT;