# This is a basic workflow to help you get started with Actions

name: Test coverage badge

# Controls when the workflow will run
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update coverage report
        uses: .github/actions/test-coverage-badge
        with:
          report: 'false'
          chart: 'false'
          amend: 'true'
